apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: xfusion

data:
  TIME_FREQ: "10"
---


apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: xfusion
spec:
  container:
  - name: time-check
    image: busybox:latest
    command:
      - sh
      - -c
      - |
        while true; do
          date >> /opt/dba/time/time-check.log; 
          sleep $TIME_FREQ; 
        done
    env:
      - name: TIME_FREQ
        valueFrom:
          configMagKeyRef:
            name: time-config
            key: TIME_FREQ
    volumeMounts:
      - name: log-volume
        mountPath: /opt/dba/time
  volumes:
    - name: log-volume
      emptyDir: {}